### PR TITLE
V2 im

### PR DESCRIPTION
**Pull request by iagomosqueira**
I have tried to get FSLAM to pass R CMD check. Still one error remains in an example

```
sam.list <- lapply(ctrls,FLSAM,stck=NSH,tun=NSH.tun)                  
```

comes back with

```
Error in solve.default(h, g) : 
  Lapack routine dgesv: system is exactly singular: U[2,2] = 0
Calls: lapply -> lapply -> FUN -> sam.fit -> solve -> solve.default
```

so maybe one on the runs is not right.

@nielshintzen Github shows it as a merge to master, but should be done to develop_V2 first

### CODE REVIEW

**Comment by nielshintzen** [comment]
The ‘update’ was missing from the section below in between the return brackets.
Thereafter it runs fine.


ctrls  <- lapply(ctrl.list,function(x) {
            tmp.ctrl <- NSH.ctrl
            tmp.ctrl@catchabilities["HERAS",ac(1:8)] <- x
            return(update(tmp.ctrl))})

**Comment by iagomosqueira** [comment]
OK, now some missing datasets. Errors in help only show up when previous errors are solved

```
> data(HERAS.sams)
Warning in data(HERAS.sams) : data set ‘HERAS.sams’ not found
> ssb(HERAS.sams)
Error in ssb(HERAS.sams) : object 'HERAS.sams' not found
```

**Comment by nielshintzen** [comment]
We can save the outputs of the example we just fixed as HERAS.sams

**Comment by iagomosqueira** [comment]
Done. One more, thing, FLSAM.control does not have the @nohess slot anymore, right? Should this simply be deleted from accesors.Rd?

```
ctrl.nohess <- NSH.ctrl
ctrl.nohess@nohess <- TRUE
```

**Comment by nielshintzen** [comment]
Correct, it’s been replaced with the @residuals slot

**Pull request merged**
