### PR TITLE
updates to stockassessment version 0.12

### PR DESCRIPTION
**Pull request by nielshintzen**
Updated FLSAM to work with latest version of SAM (0.12), updates on FLSAM.control, methods, looi, retro ect. Included option to set mapping of parameter values as part of the function call

### CODE REVIEW

**Comment by iagomosqueira** [comment]
'otolith' as called in the example

```
data(NSH.sam)
otolith(NSH.sam,year=2010,n=150)
```

fails because dimension of mu and Sigma in mvrnorm do not match

```
>       d <- mvrnorm(n=n,c(pars$value), object@rescov)
Error in mvrnorm(n = n, c(pars$value), object@rescov) :
  incompatible arguments
> dim(object@rescov)
[1] 286 286
> length(pars$value)
[1] 244
```

I have reconstructed `NHS.sam`, so the output corresponds to the new version.

Any idea what could be causing this discrepancy in dimensions?

**Comment by iagomosqueira** [comment]
Great, that works with a small fix.

`monteCarloStock` exa mple call in Rd file fails in line 56 as extracting the second chunk of the object to replicate gives an error.

```
> object$obj$simulate(unlist(object$pl))
Error in EvalDoubleFunObject(Fun, theta, do_simulate = do_simulate) :
  Wrong parameter length.
```

I checked and

```
> length(unlist(object$pl))
[1] 393
```

**Comment by iagomosqueira** [comment]
Is forecast not a function in FLSAM anymore? Or dos it come from somewhere else?

```
> fut <- forecast(sam, fscale = NULL, catchval = NULL, fval = NULL,
+   nosim = 1000, year.base = max(fit$data$years),
+   ave.years = max(fit$data$years) + (-4:0),
+   rec.years = max(fit$data$years) + (-9:0), label = NULL,
+   overwriteSelYears = NULL, deterministic = FALSE)
Error in forecast(sam, fscale = NULL, catchval = NULL, fval = NULL, nosim = 1000,  : 
  could not find function "forecast"
```

**Comment by nielshintzen** [comment]
Its never been a function of FLSAM, we’ve always used the forecast functionality in FLR

**Comment by iagomosqueira** [comment]
OK. I don't remember a forecast function or method in FLR. We will leave the example out, we don't need to add a dependency on FLasher for `fwd()` just for an example

**Comment by iagomosqueira** [comment]
The `update(FLSAM)` method is now commented out. Is it to be deleted or will come back? An example uses it, so need to stop it from running.

**Comment by nielshintzen** [comment]
I don't see the use of it anymore. In the admb time it was useful to have a pin file, now it's not really necessary anymore, so it won't come back

________________________________

**Pull request merged**
